// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5_ivmqapPvNWSEN6qrjq4ZVIIrn9GiKQ',
    appId: '1:125206673389:web:57cf599be24278f912d9e4',
    messagingSenderId: '125206673389',
    projectId: 'yoonjechoi-firebase-1',
    authDomain: 'yoonjechoi-firebase-1.firebaseapp.com',
    databaseURL: 'https://yoonjechoi-firebase-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yoonjechoi-firebase-1.appspot.com',
    measurementId: 'G-2GE6QLNT24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXvYfgSv6V-wY4OnA3Qy2Qrj73JeRl3CE',
    appId: '1:125206673389:android:1f13dd8ef59f004712d9e4',
    messagingSenderId: '125206673389',
    projectId: 'yoonjechoi-firebase-1',
    databaseURL: 'https://yoonjechoi-firebase-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yoonjechoi-firebase-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9altPB5rfRnA1A0jpd9IwyslRQ_ZkM94',
    appId: '1:125206673389:ios:812a664c4925f86712d9e4',
    messagingSenderId: '125206673389',
    projectId: 'yoonjechoi-firebase-1',
    databaseURL: 'https://yoonjechoi-firebase-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yoonjechoi-firebase-1.appspot.com',
    androidClientId: '125206673389-4shmd7j5jn5il620j2bmef66d635cc2p.apps.googleusercontent.com',
    iosClientId: '125206673389-t7rj9ikunii10hnmgk0iomi851p8jo1t.apps.googleusercontent.com',
    iosBundleId: 'io.spotu.yoonjechoi.todos',
  );
}
